# Generated by Django 4.1.7 on 2023-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author_alter_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'yello'), ('2', 'red'), ('3', 'black')], max_length=32, null=True),
        ),
    ]
