# Generated by Django 4.1.7 on 2023-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_type_article_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'bouqet'), ('2', 'plant'), ('2', 'flower')], max_length=32, null=True),
        ),
    ]
