# Generated by Django 4.1.7 on 2023-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'birthday'), ('anniversary', 'anniversary'), ('sympathy', 'sympathy'), ('graduation', 'graduation'), ('getwell', 'getwell')], max_length=32, null=True),
        ),
    ]
